@echo off 
title Bucle de ejemplo 
color F2
:bucle
echo TODOS MONOS TODOS MONOS TODOS MONOS TODOS MONOS TODOS MONOS TODOS MONOS
echo TODOS MONOS TODOS MONOS TODOS MONOS TODOS MONOS TODOS MONOS TODOS MONOS
goto bucle